# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class AnnualRainfall(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, year: int=None, amount: float=None):  # noqa: E501
        """AnnualRainfall - a model defined in Swagger

        :param year: The year of this AnnualRainfall.  # noqa: E501
        :type year: int
        :param amount: The amount of this AnnualRainfall.  # noqa: E501
        :type amount: float
        """
        self.swagger_types = {
            'year': int,
            'amount': float
        }

        self.attribute_map = {
            'year': 'year',
            'amount': 'amount'
        }
        self._year = year
        self._amount = amount

    @classmethod
    def from_dict(cls, dikt) -> 'AnnualRainfall':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The AnnualRainfall of this AnnualRainfall.  # noqa: E501
        :rtype: AnnualRainfall
        """
        return util.deserialize_model(dikt, cls)

    @property
    def year(self) -> int:
        """Gets the year of this AnnualRainfall.


        :return: The year of this AnnualRainfall.
        :rtype: int
        """
        return self._year

    @year.setter
    def year(self, year: int):
        """Sets the year of this AnnualRainfall.


        :param year: The year of this AnnualRainfall.
        :type year: int
        """

        self._year = year

    @property
    def amount(self) -> float:
        """Gets the amount of this AnnualRainfall.

        Rainfall amount in mm  # noqa: E501

        :return: The amount of this AnnualRainfall.
        :rtype: float
        """
        return self._amount

    @amount.setter
    def amount(self, amount: float):
        """Sets the amount of this AnnualRainfall.

        Rainfall amount in mm  # noqa: E501

        :param amount: The amount of this AnnualRainfall.
        :type amount: float
        """

        self._amount = amount
