# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class MonthlyAverage(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, month: str=None, month_no: int=None, amount: float=None):  # noqa: E501
        """MonthlyAverage - a model defined in Swagger

        :param month: The month of this MonthlyAverage.  # noqa: E501
        :type month: str
        :param month_no: The month_no of this MonthlyAverage.  # noqa: E501
        :type month_no: int
        :param amount: The amount of this MonthlyAverage.  # noqa: E501
        :type amount: float
        """
        self.swagger_types = {
            'month': str,
            'month_no': int,
            'amount': float
        }

        self.attribute_map = {
            'month': 'month',
            'month_no': 'monthNo',
            'amount': 'amount'
        }
        self._month = month
        self._month_no = month_no
        self._amount = amount

    @classmethod
    def from_dict(cls, dikt) -> 'MonthlyAverage':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The MonthlyAverage of this MonthlyAverage.  # noqa: E501
        :rtype: MonthlyAverage
        """
        return util.deserialize_model(dikt, cls)

    @property
    def month(self) -> str:
        """Gets the month of this MonthlyAverage.

        Shortened month name  # noqa: E501

        :return: The month of this MonthlyAverage.
        :rtype: str
        """
        return self._month

    @month.setter
    def month(self, month: str):
        """Sets the month of this MonthlyAverage.

        Shortened month name  # noqa: E501

        :param month: The month of this MonthlyAverage.
        :type month: str
        """

        self._month = month

    @property
    def month_no(self) -> int:
        """Gets the month_no of this MonthlyAverage.

        Month number (1-12)  # noqa: E501

        :return: The month_no of this MonthlyAverage.
        :rtype: int
        """
        return self._month_no

    @month_no.setter
    def month_no(self, month_no: int):
        """Sets the month_no of this MonthlyAverage.

        Month number (1-12)  # noqa: E501

        :param month_no: The month_no of this MonthlyAverage.
        :type month_no: int
        """

        self._month_no = month_no

    @property
    def amount(self) -> float:
        """Gets the amount of this MonthlyAverage.

        Rainfall amount in mm  # noqa: E501

        :return: The amount of this MonthlyAverage.
        :rtype: float
        """
        return self._amount

    @amount.setter
    def amount(self, amount: float):
        """Sets the amount of this MonthlyAverage.

        Rainfall amount in mm  # noqa: E501

        :param amount: The amount of this MonthlyAverage.
        :type amount: float
        """

        self._amount = amount
